import Mathlib.InformationTheory.KullbackLeibler.DataProcessing
import Mathlib.Probability.Kernel.Composition.Lemmas

open MeasureTheory ProbabilityTheory
open scoped ENNReal ProbabilityTheory

namespace Formal.Information

/-- Joint-versus-product-marginals KL mutual information of a source and its Markov output.
For a probability source and Markov kernel the joint law is `μ ⊗ₘ κ`, with marginals
`μ` and `κ ∘ₘ μ`. The value may be infinite. -/
noncomputable def mutualInformation {X Y : Type*} [MeasurableSpace X] [MeasurableSpace Y]
    (μ : Measure X) (κ : Kernel X Y) : ℝ≥0∞ :=
  InformationTheory.klDiv (μ ⊗ₘ κ) (μ.prod (κ ∘ₘ μ))

/-- KL contraction under a common stochastic channel, retained under its precise name. -/
theorem kl_markov_dpi {X Y : Type*} [MeasurableSpace X] [MeasurableSpace Y]
    (μ ν : Measure X) [IsFiniteMeasure μ] [IsFiniteMeasure ν]
    (κ : Kernel X Y) [IsMarkovKernel κ] :
    InformationTheory.klDiv (κ ∘ₘ μ) (κ ∘ₘ ν) ≤ InformationTheory.klDiv μ ν :=
  InformationTheory.klDiv_comp_right_le μ ν κ

/-- Mutual-information Markov DPI for the chain generated by `μ`, `κ : X → Y`,
and `η : Y → Z`: `I(X;Z) ≤ I(X;Y)`. Both joint and product marginal laws are sent
through the same channel that retains X and applies η to Y. -/
theorem markov_dpi {X Y Z : Type*}
    [MeasurableSpace X] [MeasurableSpace Y] [MeasurableSpace Z]
    (μ : Measure X) [IsProbabilityMeasure μ]
    (κ : Kernel X Y) (η : Kernel Y Z) [IsMarkovKernel κ] [IsMarkovKernel η] :
    mutualInformation μ (η ∘ₖ κ) ≤ mutualInformation μ κ := by
  have h := InformationTheory.klDiv_comp_right_le
    (μ ⊗ₘ κ) (μ.prod (κ ∘ₘ μ)) (Kernel.id ∥ₖ η)
  simpa only [mutualInformation, Measure.parallelComp_comp_compProd,
    ← Measure.prod_comp_right, Measure.comp_assoc] using h

end Formal.Information
